version: "3.1"

services:
  contracts-api:
    container_name: contracts-api
    restart: on-failure
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    networks:
      - printgo_network

networks:
  printgo_network:
    name: printgo_network
    driver: bridge