services:
  contracts-api:
    container_name: contracts-api
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - .:/src
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DOCKER_URL}
    networks:
      - printgo_network
    depends_on: 
      - contracts-db
    command: ["sh", "-c", "npx prisma db push && npm run dev"]
  contracts-db:
    image: postgres:13
    container_name: contracts-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - printgo_network
    

networks:
  printgo_network:
    name: printgo_network
    driver: bridge
    external: true
volumes:
  db-data:
    driver: local