services:
  contracts-api:
    container_name: contracts-api
    restart: on-failure
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - .:/src
    ports:
      - "8001:8000"
    networks:
      - printgo_network
  contracts-db:
    image: postgres:13
    container_name: contracs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - printgo_network
    

networks:
  printgo_network:
    name: printgo_network
    driver: bridge
    external: true