name: Análise de Código
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres:latest
            env:
              POSTGRES_DB: testdb
              POSTGRES_USER: testuser
              POSTGRES_PASSWORD: testpassword
            ports:
              - 5444:5432
            options: >-
              --health-cmd="pg_isready -U testuser -d testdb"
              --health-interval=10s
              --health-timeout=5s
              --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Instala dependências
        run: npm install

      - name: Executa testes e gera cobertura
        run: npm run test:all
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5444/testdb

      - name: Executa SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}